### ISSUE TITLE
Druckvorschaurahmen wird nicht berücksichtigt

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-printing-enhanced#12]
Im Druckdialog wird der Vorschaurahmen des Ausdruckes in der Karte dargestellt. Bei der Druckerstellung wird der maximale horizontal sichtbare Kartenausschnitt gedruckt und nicht nur der gewünschte Bereich des Druckvorschaurahmens. Legt der Nutzer jedoch ein Maßstab fest, wird ausschließlich der Inhalt des Druckvorschaurahmens gedruckt, was richtig ist.
Das erwartete Verhalten wäre, dass immer nur der Inhalt des dargestellten Druckvorschaurahmens ausgegeben, oder der Vorschaurahmen in dem Fall nicht dargestellt wird.

Ergebnis:
![Printing_Dialog](https://github.com/conterra/mapapps-printing-enhanced/assets/60434030/3dad9fe6-3908-4016-99a0-eac702ca9aad)
![Printing_Ergebnis](https://github.com/conterra/mapapps-printing-enhanced/assets/60434030/552a7535-5e2e-4c96-a9e9-55b5b68c729c)

**Comment by sholtkamp** [comment]
Hallo Herr Backhaus,
ich kann das von Ihnen beschriebene Problem in unserer Demo-App nicht nachstellen.
Können Sie das Problem in der Demo-App replizieren? Diese finden Sie unter: [Demo-App](https://demos.conterra.de/mapapps/resources/apps/downloads_printingenhanced/index.html)

Um das Problem weiter einzugrenzen, könnten Sie uns mit folgenden Informationen noch weiterhelfen:
- Wurde der verwendete Druckdienst mit ArcGIS Map oder ArcGIS Pro aufgesetzt?
- Welcher Version von ArcGIS Server wird aktuell genutzt?

**Comment by gedicb** [comment]
Hallo Herr Holtkamp,

das Verhalten können Sie mit dieser Beispiel-App nachvollziehen:
https://gdi.gelsenkirchen.de/mapapps/resources/apps/x_cb_APPSTATE415/index.html?lang=de

Aktuell nutzen wir den ArcGIS Server 10.8.1 und der Druckdienst wurde mit ArcGIS Pro 2.9.5 aufgesetzt.

In Ihrer Demo-App ist unter den „templateOptions“ die Property „scale“ und „scaleEnabled“ gesetzt. Damit geht es. Ich vermute, wenn die beiden Parameter nicht vorhanden sind müsste hier das beschriebene Verhalten auch auftreten.


Mit freundlichen Grüßen
Im Auftrag


Carsten Backhaus

Stadt Gelsenkirchen
Die Oberbürgermeisterin
Referat 62 Vermessung und Kataster
Goldbergstraße 12

Telefon: 0209 169-4203
Telefax: 0209 169-4816

***@***.***

Von: Sebastian Holtkamp ***@***.***>
Gesendet: Donnerstag, 14. September 2023 11:50
An: conterra/mapapps-printing-enhanced ***@***.***>
Cc: Backhaus Carsten ***@***.***>; Author ***@***.***>
Betreff: Re: [conterra/mapapps-printing-enhanced] Druckvorschaurahmen wird nicht berücksichtigt (Issue #12)


Hallo Herr Backhaus,
ich kann das von Ihnen beschriebene Problem in unserer Demo-App nicht nachstellen.
Können Sie das Problem in der Demo-App replizieren? Diese finden Sie unter: Demo-App<https://demos.conterra.de/mapapps/resources/apps/downloads_printingenhanced/index.html>

Um das Problem weiter einzugrenzen, könnten Sie uns mit folgenden Informationen noch weiterhelfen:

  *   Wurde der verwendete Druckdienst mit ArcGIS Map oder ArcGIS Pro aufgesetzt?
  *   Welcher Version von ArcGIS Server wird aktuell genutzt?

**Comment by sholtkamp** [comment]
Hallo Herr Backhaus,

vielen Dank für die von Ihnen bereitgestellten Informationen und Hinweise.

Wir konnten inzwischen die Ursache des Problems feststellen:
Mit Version 4.22 des ArcGIS Maps SDK for JavaScript gab es eine [Änderung](https://developers.arcgis.com/javascript/latest/4.22/#print-widget) im Verhalten des Print Widgets. Diese wirkt sich bedingt durch Ihr Update der map.apps Version nun bei Ihnen aus.

Wir werden in Kürze eine neue Version des Bundles Printing Enhanced veröffentlichen, welche das Fehlverhalten behebt.
