### ISSUE TITLE
Dateiname des PDF-Dokumentes

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-printing-enhanced#4]
Im Druckdialog kann ein Titel eingetragen werden. Dieser Titel wird in den Ergebnis-Tab übernommen und es steht das Dokument **titel.pdf** zum Download zur Verfügung. Die heruntergeladene Datei erhält systemseitig aber dann wieder eine abweichende  Benennung z.B. **x_____xsJm_6ylOoAUhl7bzx4mC4w..x_____x_ags_5747b19c-7a9f-11ec-a0cd-22000a88f94a.pdf**
Hier wäre es wünschenswert, wenn der anzeigte Dokumentenname mit der erzeugten PDF-Dokumentenbenennung übereinstimmen würde.

Wir nutzen map.apps 4.11.1 und das mapapps-printing-enhanced 2.0.3

**Comment by sholtkamp** [comment]
Die gewünschte Änderung des Dateinamens des PDF-Dokuments kann seitens map.apps nicht umgesetzt werden, da es notwendig ist, dass die Applikation und der PrintService auf dem gleichen Origin laufen.
Siehe: https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Print-TemplateOptions.html#fileName
