### ISSUE TITLE
Widget layout breaks on theme change in map.apps 4.12.3

### ISSUE THREAD

**Issue by sholtkamp** [conterra/mapapps-printing-enhanced#5]
When using the theme selector to change the apps theme the layout of the PrintingEnhanced widget breaks.
It does not matter whether the widget is open or minimized during the theme change.

Steps to replicate:
- Add secondary theme and theme bundles to local sample app
- Start sample app 
- Switch themes using theme selector
- Observe broken widget layout

**Comment by matthiasstein** [comment]
I can no longer reproduce this error in 4.13.
