### ISSUE TITLE
WMS-Legende fehlt beim Drucken

### ISSUE THREAD

**Issue by Michael-Bender** [conterra/mapapps-printing-enhanced#9]
Hallo Herr Stein,

wir setzen map.apps 4.11.1 ein und nutzen das Bundle "dn_printingenhanced". Außerdem haben wir einen Druckservice mit ArcGIS Pro / ArcGIS Server 9.1 veröffentlicht.

Wir haben folgendes Problem: Wenn WMS-Dienste in der App sichtbar geschaltet sind, werden diese auch auf der Karte der Druckausgabe dargestellt. Es fehlt jedoch die Legende in der Druckausgabe bzw. im PDF.

In dem Print-Request wird im Parameter "Web_Map_as_JSON" keine Anforderung zum Drucken der Legende für den WMS übergeben, der Teil des JSON-Abschnitt sieht so aus: "legendOptions":{"operationalLayers":[]}
(es wird also eine leere Liste übergeben, Test mit nur einem sichtbaren WMS-Layer).

Wenn man das WebInterface des Dienstes bemüht und innerhalb der eckigen Klammer im  folgendes ergänzt:
"legendOptions":{"operationalLayers":[{ "id": "WMS_erosionsatlas_A1","subLayerIds": ["13"]}]}

Wird die Legende des WMS-Layers gedruckt bzw. in das PDF geschrieben.

 Gibt es dafür eine möglichst einfache Lösung durch z.B. Konfiguration von "printing" oder "dn_printingenhanced"?

**Comment by dpayk** [comment]
Dieses Problem ist auch im Standard-Produkt, sowie in der Esri JS API zu beobachten und wurde als Issue MAPAPPS-6601 erfasst und an Esri berichtet.

**Comment by dpayk** [comment]
Inzwischen haben wir die Rückmeldung bekommen, dass das Problem im ArcGIS Maps SDK for JavaScript 4.27 gefixt wird. Diese Version ist aktuell noch nicht verfügbar. (BUG-000154383 - WMSLayer is not included in legendOptions when printed from the Print widget.)

**Comment by sholtkamp** [comment]
Fixed in map.apps version 4.16.0.
Please reopen this issue if the error persists on your end.
